language: cpp
compiler: gcc
sudo: require
dist: trusty
before_install:
- sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
- sudo apt-get update
- mkdir -p appdir/usr/bin
- mkdir -p appdir/usr/translations
install:
- sudo apt-get -y install qt510base qt510svg qt510translations qt510tools libgl1-mesa-dev libgtk2.0-dev git
- source /opt/qt*/bin/qt*-env.sh
script:
- lupdate ChessTrainingVsEngine.pro
- lrelease ChessTrainingVsEngine.pro
- qmake CONFIG+=release PREFIX=/usr
- make -j$(nproc)
- make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
- cp appdir/opt/ChessTrainingVsEngine/bin/ChessTrainingVsEngine appdir/usr/bin
- cp /home/travis/build/loloof64/ChessTrainingVsEngine/resources/translations/*.qm appdir/usr/translations
- git clone http://code.qt.io/qt/qtstyleplugins.git
- cd qtstyleplugins
- qmake
- make -j$(nproc)
- sudo make install
- cd -
- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
- "./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop
  -bundle-non-qt-libs -verbose=1"
- "./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop
  -appimage -verbose=1"
after_success:
- mv Chess_Pgn_Reviser*.AppImage ChessTrainingVsEngine-Linux-x86_64.AppImage
- chmod a+x ChessTrainingVsEngine-Linux-x86_64.AppImage
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- bash upload.sh ChessTrainingVsEngine-Linux-x86_64.AppImage

before_deploy:
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file: ChessTrainingVsEngine-Linux-x86_64.AppImage
  on:
    tags: true
  skip_cleanup: true
